### PR TITLE
fix: broken ndjson implementation

### LINKED ISSUE #17: TypeError when using `-n` CLI flag
When using `-n` CLI flag, the following error is thrown: `TypeError: ndjson is not a function`

This regression likely happened after upgrading `ndjson` package from version `1.x.x` to version `2.x.x`, where the API of the package changed. The error takes place in the following two places:
https://github.com/sanity-io/groq-cli/blob/c726590f441214092ee37c3ec1adb2f256cb36a6/src/cli.js#L132
https://github.com/sanity-io/groq-cli/blob/c726590f441214092ee37c3ec1adb2f256cb36a6/src/cli.js#L108

### PR DESCRIPTION
**Pull request by rexxars**
Fixes #17

Was broken by https://github.com/sanity-io/groq-cli/commit/e5e7e57b1eaa768f9c7457d7b26d101f685966fb upgrading the major of `ndjson` without updating the API.

### CODE REVIEW

File: src/cli.js [hunk 1]
```diff
@@ -105,13 +105,15 @@ async function* outputPrettyJSON(result) {
...
+    for await (const row of value) {
+      yield JSON.stringify(row)
       yield '\n'
     }
   } else {
-    yield JSON.stringify(await result.get())
+    yield JSON.stringify(value)
     yield '\n'
   }
 }
```
Comment (sgulseth) [inline src/cli.js:119]: I think all we want to do is change L108 to `if (result.type == 'stream') {` that way we stream the values per document in the resulting query

The proposed solution would turn any arrays into ndjson separated list, `echo '{\"foo\": [1,2,3,4]}\n{\"bar\": [2]}' | ./bin/groq.js -n --pretty '*[][0].foo'` would return '1\n2\n3\n4` instead of `[1,2,3,4]`

**Review by sgulseth — CHANGES_REQUESTED** [review]
